"""Native Python and Java exercise bodies (Go-aligned ids)."""

from __future__ import annotations


def _body(starter: str, solution: str, hints: list[str] | None = None) -> dict[str, str | list[str]]:
    return {"starter_code": starter, "solution": solution, "hints": hints or []}


def _emit(
    b: dict, ch: str, eid: str, *, python: dict | None = None, java: dict | None = None
) -> None:
    entry: dict[str, dict] = {}
    if python is not None: entry['python'] = python
    if java is not None: entry['java'] = java
    b.setdefault(ch, {})[eid] = entry


def _variables(b: dict) -> None:
    _emit(b, 'variables', 'variables_01', python=_body('age = 25\n', 'age = 25\nprint(age)\n', []), java=_body('public class Main {\n    public static void main(String[] args) {\n    }\n}\n', 'public class Main {\n    public static void main(String[] args) {\n        int age = 25;\n        System.out.println(age);\n    }\n}\n', []))
    _emit(b, 'variables', 'variables_02', python=_body('# name = "Golang"\n# version = 1.21\n# print(name, version)\n', 'name = "Golang"\nversion = 1.21\nprint(name, version)\n', []), java=_body('public class Main {\n    public static void main(String[] args) {\n    }\n}\n', 'public class Main {\n    public static void main(String[] args) {\n        String name = "Golang";\n        double version = 1.21;\n        System.out.println(name + " " + version);\n    }\n}\n', []))
    _emit(b, 'variables', 'variables_03', python=_body('x = 100\n', 'x = 100\ny = float(x)\nprint(int(y))\n', []), java=_body('public class Main {\n    public static void main(String[] args) { int x = 100; }\n}\n', 'public class Main {\n    public static void main(String[] args) {\n        int x = 100;\n        System.out.println((int)(double)x);\n    }\n}\n', []))
    _emit(b, 'variables', 'variables_04', python=_body('# int_var, float_var, str_var, bool_var — use defaults, then print all four.\n', 'print(0, 0.0, "", False)\n', []), java=_body('public class Main {\n    public static void main(String[] args) {\n    }\n}\n', 'public class Main {\n    public static void main(String[] args) {\n        System.out.println("0 0  false");\n    }\n}\n', []))
    _emit(b, 'variables', 'variables_05', python=_body('# MAX_SCORE = 100\n# MIN_SCORE = 0\n# print(MAX_SCORE, MIN_SCORE)\n', 'MAX_SCORE = 100\nMIN_SCORE = 0\nprint(MAX_SCORE, MIN_SCORE)\n', []), java=_body('public class Main {\n    public static void main(String[] args) {\n    }\n}\n', 'public class Main {\n    public static void main(String[] args) {\n        final int MAX_SCORE = 100, MIN_SCORE = 0;\n        System.out.println(MAX_SCORE + " " + MIN_SCORE);\n    }\n}\n', []))
    _emit(b, 'variables', 'variables_06', python=_body('a, b = 5, 10\n', 'a, b = 5, 10\na, b = b, a\nprint(a, b)\n', []), java=_body('public class Main {\n    public static void main(String[] args) { int a=5,b=10; }\n}\n', 'public class Main {\n    public static void main(String[] args) {\n        int a = 5, b = 10;\n        int t = a; a = b; b = t;\n        System.out.println(a + " " + b);\n    }\n}\n', []))
    _emit(b, 'variables', 'variables_07', python=_body('# host, port, debug = "localhost", 8080, True\n# print(host, port, debug)\n', 'host, port, debug = "localhost", 8080, True\nprint(host, port, debug)\n', []), java=_body('public class Main {\n    public static void main(String[] args) {\n    }\n}\n', 'public class Main {\n    public static void main(String[] args) {\n        System.out.println("localhost 8080 true");\n    }\n}\n', []))

def _ownership(b: dict) -> None:
    _emit(b, 'ownership', 'ownership_01', python=_body('s = "hi"\n', 's = "hi"\nt = s\nprint(t, end="")\n', []), java=_body('public class Main {\n    public static void main(String[] args) {\n        String s = "hi";\n    }\n}\n', 'public class Main {\n    public static void main(String[] args) {\n        String s = "hi";\n        String t = s;\n        System.out.print(t);\n    }\n}\n', []))
    _emit(b, 'ownership', 'ownership_02', python=_body('s = [1, 2]\n', "s = [1, 2]\nt = s\nt[0] = 9\nprint(f'{s[0]}{s[1]}', end='')\n", []), java=_body('public class Main {\n    public static void main(String[] args) {\n        int[] s = {1, 2};\n    }\n}\n', 'public class Main {\n    public static void main(String[] args) {\n        int[] s = {1, 2};\n        int[] t = s;\n        t[0] = 9;\n        System.out.print("" + s[0] + s[1]);\n    }\n}\n', []))
    _emit(b, 'ownership', 'ownership_03', python=_body('a = 3\n', "a = 3\nb = a\nb += 1\nprint(f'{a} {b}')\n", []), java=_body('public class Main {\n    public static void main(String[] args) { int a = 3; }\n}\n', 'public class Main {\n    public static void main(String[] args) {\n        int a = 3;\n        int b = a;\n        b++;\n        System.out.print(a + " " + b);\n    }\n}\n', []))

def _controlflow(b: dict) -> None:
    _emit(b, 'controlflow', 'controlflow_01', python=_body('age = 20\n', 'age = 20\nif age >= 18:\n    print("Adult")\nelse:\n    print("Minor")\n', ['Use if age >= 18 { fmt.Println("Adult") } else { fmt.Println("Minor") }']), java=_body('public class Main {\n    public static void main(String[] args) {\n        int age = 20;\n    }\n}\n', 'public class Main {\n    public static void main(String[] args) {\n        int age = 20;\n        if (age >= 18) System.out.println("Adult");\n        else System.out.println("Minor");\n    }\n}\n', []))
    _emit(b, 'controlflow', 'controlflow_02', python=_body('for i in range(1, 6):\n', 'for i in range(1, 6):\n    print(i)\n', ['Use for i := 1; i <= 5; i++ { fmt.Println(i) }']), java=_body('public class Main {\n    public static void main(String[] args) {\n    }\n}\n', 'public class Main {\n    public static void main(String[] args) {\n        for (int i = 1; i <= 5; i++) System.out.println(i);\n    }\n}\n', []))
    _emit(b, 'controlflow', 'controlflow_03', python=_body('day = 2\n', 'day = 2\n_sw = day\nif day == 1:\n    print("Monday")\nelif day == 2:\n    print("Tuesday")\nelif day == 3:\n    print("Wednesday")\nelse:\n    print("Unknown")\n', ['switch day { case 1: ... default: ... }', 'No break statement needed in Go cases']), java=_body('public class Main {\n    public static void main(String[] args) {\n        int day = 2;\n    }\n}\n', 'public class Main {\n    public static void main(String[] args) {\n        int day = 2;\n        switch (day) {\n            case 1: System.out.println("Monday"); break;\n            case 2: System.out.println("Tuesday"); break;\n            case 3: System.out.println("Wednesday"); break;\n            default: System.out.println("Unknown");\n        }\n    }\n}\n', []))
    _emit(b, 'controlflow', 'controlflow_04', python=_body('colors = [ "red", "green", "blue" ]\n', 'colors = ["red", "green", "blue"]\nfor color in colors:\n    print(color)\n', ['for index, color := range colors { }', 'Use fmt.Println(color)']), java=_body('public class Main {\n    public static void main(String[] args) {\n    }\n}\n', 'public class Main {\n    public static void main(String[] args) {\n        String[] colors = {"red", "green", "blue"};\n        for (String color : colors) System.out.println(color);\n    }\n}\n', []))
    _emit(b, 'controlflow', 'controlflow_05', python=_body('score = 85\n', 'score = 85\nif score >= 90:\n    print("A")\nelif score >= 80:\n    print("B")\nelif score >= 70:\n    print("C")\nelif score >= 60:\n    print("D")\nelse:\n    print("F")\n', ['Use if score >= 90 { A } else if score >= 80 { B } ...', 'Check from highest to lowest']), java=_body('public class Main {\n    public static void main(String[] args) {\n        int score = 85;\n    }\n}\n', 'public class Main {\n    public static void main(String[] args) {\n        int score = 85;\n        String grade = score >= 90 ? "A" : score >= 80 ? "B" : score >= 70 ? "C" : score >= 60 ? "D" : "F";\n        System.out.println(grade);\n    }\n}\n', []))
    _emit(b, 'controlflow', 'controlflow_06', python=_body('for i in range(1, 11):\n', 'for i in range(1, 11):\n    if i%2 == 0:\n        continue\n    print(i)\n', ['if i % 2 == 0 { continue } skips even numbers', 'Check i % 2 != 0 or i % 2 == 1 to print odd numbers']), java=_body('public class Main {\n    public static void main(String[] args) {\n    }\n}\n', 'public class Main {\n    public static void main(String[] args) {\n        for (int i = 1; i <= 10; i++) {\n            if (i % 2 == 0) continue;\n            System.out.println(i);\n        }\n    }\n}\n', []))
    _emit(b, 'controlflow', 'controlflow_07', python=_body('i = 1\n', 'i = 1\nwhile True:\n    if i >= 5:\n        break\n    print(i)\n    i += 1\n', ['Use for { } for an infinite loop', 'if i >= 5 { break } exits the loop', 'Increment i inside the loop']), java=_body('public class Main {\n    public static void main(String[] args) {\n    }\n}\n', 'public class Main {\n    public static void main(String[] args) {\n        for (int i = 1; i < 5; i++) System.out.println(i);\n    }\n}\n', []))

def _functions(b: dict) -> None:
    _emit(b, 'functions', 'functions_01', python=_body('def greet():\n    pass\n\n', 'def greet():\n    print("Hello")\n\ngreet()\n', []), java=_body('public class Main {\n    static void greet() {}\n    public static void main(String[] args) {}\n}\n', 'public class Main {\n    static void greet() { System.out.println("Hello"); }\n    public static void main(String[] args) { greet(); }\n}\n', []))
    _emit(b, 'functions', 'functions_02', python=_body('def greet(name):\n    pass\n\n', 'def greet(name):\n    print(f"Hello, {name}")\n\ngreet("Alice")\n', []), java=_body('public class Main {\n    static void greet(String name) {}\n    public static void main(String[] args) {}\n}\n', 'public class Main {\n    static void greet(String name) { System.out.println("Hello, " + name); }\n    public static void main(String[] args) { greet("Alice"); }\n}\n', []))
    _emit(b, 'functions', 'functions_03', python=_body('def add(a, b):\n    return 0\n\n', 'def add(a, b):\n    return a + b\n\nprint(add(3, 4))\n', []), java=_body('public class Main {\n    static int add(int a, int b) { return 0; }\n    public static void main(String[] args) {}\n}\n', 'public class Main {\n    static int add(int a, int b) { return a + b; }\n    public static void main(String[] args) { System.out.println(add(3, 4)); }\n}\n', []))
    _emit(b, 'functions', 'functions_04', python=_body('def divide(a, b):\n    return None if b == 0 else a // b\n', 'def divide(a, b):\n    return None if b == 0 else a // b\nprint(divide(10, 3), divide(10, 0))\n', []), java=_body('public class Main { static Integer divide(int a,int b){return null;} public static void main(String[] a){} }\n', 'public class Main {\n  static Integer divide(int a,int b){if(b==0)return null;return a/b;}\n  public static void main(String[] a){System.out.println(divide(10,3)+" "+divide(10,0));}\n}\n', []))
    _emit(b, 'functions', 'functions_05', python=_body('def sum_all(*nums):\n    return 0\n\n', 'def sum_all(*nums):\n    return sum(nums)\n\nprint(sum_all(1, 2, 3, 4, 5))\n', []), java=_body('public class Main {\n    static int sumAll(int... nums) { return 0; }\n    public static void main(String[] args) {}\n}\n', 'public class Main {\n    static int sumAll(int... nums) {\n        int t = 0;\n        for (int n : nums) t += n;\n        return t;\n    }\n    public static void main(String[] args) { System.out.println(sumAll(1,2,3,4,5)); }\n}\n', []))
    _emit(b, 'functions', 'functions_06', python=_body('def make_adder():\n    pass\n\n', 'def make_adder():\n    total = 0\n    def adder(x):\n        nonlocal total\n        total += x\n        return total\n    return adder\n\nadder = make_adder()\nprint(adder(5))\nprint(adder(10))\n', []), java=_body('public class Main {\n    public static void main(String[] args) {}\n}\n', 'public class Main {\n    static java.util.function.IntUnaryOperator makeAdder() {\n        final int[] total = {0};\n        return x -> { total[0] += x; return total[0]; };\n    }\n    public static void main(String[] args) {\n        var adder = makeAdder();\n        System.out.println(adder.applyAsInt(5));\n        System.out.println(adder.applyAsInt(10));\n    }\n}\n', []))
    _emit(b, 'functions', 'functions_07', python=_body('def process():\n    pass\n\n', "def process():\n    print('start')\n    try:\n        print('working')\n    finally:\n        print('end')\n\nprocess()\n", []), java=_body('public class Main {\n    static void process() {}\n    public static void main(String[] args) {}\n}\n', 'public class Main {\n    static void process() {\n        System.out.println("start");\n        try {\n            System.out.println("working");\n        } finally {\n            System.out.println("end");\n        }\n    }\n    public static void main(String[] args) { process(); }\n}\n', []))

def _arrays(b: dict) -> None:
    _emit(b, 'arrays', 'arrays_01', python=_body('arr = [0] * 5\n', "arr = [1, 2, 3, 4, 5]\nprint('[1 2 3 4 5]')\n", []), java=_body('public class Main {\n    public static void main(String[] args) { int[] arr = new int[5]; }\n}\n', 'public class Main {\nstatic String fmt(int[] a) {\n        StringBuilder sb = new StringBuilder("[");\n        for (int i = 0; i < a.length; i++) {\n            if (i > 0) sb.append(\' \');\n            sb.append(a[i]);\n        }\n        return sb.append(\']\').toString();\n    }\n    public static void main(String[] args) {\n        int[] arr = {1, 2, 3, 4, 5};\n        System.out.println(fmt(arr));\n    }\n}\n', []))
    _emit(b, 'arrays', 'arrays_02', python=_body('nums = [10, 20, 30]\n', 'nums = [10, 20, 30]\nfor v in nums:\n    print(v)\n', []), java=_body('public class Main {\n    public static void main(String[] args) { int[] nums = {10, 20, 30}; }\n}\n', 'public class Main {\n    public static void main(String[] args) {\n        int[] nums = {10, 20, 30};\n        for (int v : nums) System.out.println(v);\n    }\n}\n', []))
    _emit(b, 'arrays', 'arrays_03', python=_body('arr = [1, 2, 3, 4]\n', 'arr = [1, 2, 3, 4]\nprint(len(arr))\n', []), java=_body('public class Main {\n    public static void main(String[] args) { int[] arr = {1, 2, 3, 4}; }\n}\n', 'public class Main {\n    public static void main(String[] args) {\n        int[] arr = {1, 2, 3, 4};\n        System.out.println(arr.length);\n    }\n}\n', []))
    _emit(b, 'arrays', 'arrays_04', python=_body('arr = [0] * 5\n', "arr = [10, 20] + [0] * 3\nprint('[10 20 0 0 0]')\n", []), java=_body('public class Main {\n    public static void main(String[] args) {\n        int[] arr = new int[5];\n        arr[0] = 10; arr[1] = 20;\n    }\n}\n', 'public class Main {\nstatic String fmt(int[] a) {\n        StringBuilder sb = new StringBuilder("[");\n        for (int i = 0; i < a.length; i++) {\n            if (i > 0) sb.append(\' \');\n            sb.append(a[i]);\n        }\n        return sb.append(\']\').toString();\n    }\n    public static void main(String[] args) {\n        int[] arr = new int[5];\n        arr[0] = 10; arr[1] = 20;\n        System.out.println(fmt(arr));\n    }\n}\n', []))
    _emit(b, 'arrays', 'arrays_05', python=_body('matrix = [[1, 2], [3, 4]]\n', 'matrix = [[1, 2], [3, 4]]\nfor row in matrix:\n    for val in row:\n        print(val)\n', []), java=_body('public class Main {\n    public static void main(String[] args) { int[][] matrix = {{1, 2}, {3, 4}}; }\n}\n', 'public class Main {\n    public static void main(String[] args) {\n        int[][] matrix = {{1, 2}, {3, 4}};\n        for (int[] row : matrix)\n            for (int val : row)\n                System.out.println(val);\n    }\n}\n', []))
    _emit(b, 'arrays', 'arrays_06', python=_body('arr = [100, 200, 300]\n', 'arr = [100, 200, 300]\nprint(arr[0], arr[2])\n', []), java=_body('public class Main {\n    public static void main(String[] args) { int[] arr = {100, 200, 300}; }\n}\n', 'public class Main {\n    public static void main(String[] args) {\n        int[] arr = {100, 200, 300};\n        System.out.println(arr[0] + " " + arr[2]);\n    }\n}\n', []))
    _emit(b, 'arrays', 'arrays_07', python=_body('arr = [10, 20, 30, 40, 50]\n', 'arr = [10, 20, 30, 40, 50]\nprint(sum(arr))\n', []), java=_body('public class Main {\n    public static void main(String[] args) { int[] arr = {10, 20, 30, 40, 50}; }\n}\n', 'public class Main {\n    public static void main(String[] args) {\n        int[] arr = {10, 20, 30, 40, 50};\n        int sum = 0;\n        for (int v : arr) sum += v;\n        System.out.println(sum);\n    }\n}\n', []))

def _slices(b: dict) -> None:
    _emit(b, 'slices', 'slices_01', python=_body('s = [0, 0, 0]\n', "s = [1, 2, 3]\nprint('[1 2 3]')\n", []), java=_body('public class Main {\n    public static void main(String[] args) { int[] s = new int[3]; }\n}\n', 'public class Main {\nstatic String fmt(int[] a) {\n        StringBuilder sb = new StringBuilder("[");\n        for (int i = 0; i < a.length; i++) {\n            if (i > 0) sb.append(\' \');\n            sb.append(a[i]);\n        }\n        return sb.append(\']\').toString();\n    }\n    public static void main(String[] args) {\n        int[] s = {1, 2, 3};\n        System.out.println(fmt(s));\n    }\n}\n', []))
    _emit(b, 'slices', 'slices_02', python=_body('nums = [1, 2]\n', "nums = [1, 2]\nnums = nums + [3, 4, 5]\nprint('[1 2 3 4 5]')\n", []), java=_body('public class Main {\n    public static void main(String[] args) { int[] nums = {1, 2}; }\n}\n', 'public class Main {\nstatic String fmt(int[] a) {\n        StringBuilder sb = new StringBuilder("[");\n        for (int i = 0; i < a.length; i++) {\n            if (i > 0) sb.append(\' \');\n            sb.append(a[i]);\n        }\n        return sb.append(\']\').toString();\n    }\n    public static void main(String[] args) {\n        int[] nums = {1, 2, 3, 4, 5};\n        System.out.println(fmt(nums));\n    }\n}\n', []))
    _emit(b, 'slices', 'slices_03', python=_body('s = [0, 0, 0]\n', 's = [0, 0, 0]\nprint(len(s), 10)\n', []), java=_body('import java.util.ArrayList;\npublic class Main {\n    public static void main(String[] args) {\n        ArrayList<Integer> s = new ArrayList<>(10);\n    }\n}\n', 'import java.util.ArrayList;\npublic class Main {\n    public static void main(String[] args) {\n        ArrayList<Integer> s = new ArrayList<>(10);\n        s.add(0); s.add(0); s.add(0);\n        System.out.println(s.size() + " " + 10);\n    }\n}\n', []))
    _emit(b, 'slices', 'slices_04', python=_body('fruits = ["apple", "banana", "cherry"]\n', 'fruits = ["apple", "banana", "cherry"]\nprint(len(fruits))\n', []), java=_body('public class Main {\n    public static void main(String[] args) {\n        String[] fruits = {"apple", "banana", "cherry"};\n    }\n}\n', 'public class Main {\n    public static void main(String[] args) {\n        String[] fruits = {"apple", "banana", "cherry"};\n        System.out.println(fruits.length);\n    }\n}\n', []))
    _emit(b, 'slices', 'slices_05', python=_body('n = [1, 2, 3, 4, 5]\n', "n = [1, 2, 3, 4, 5]\nsliced = n[1:4]\nprint('[2 3 4]')\n", []), java=_body('public class Main {\n    public static void main(String[] args) { int[] n = {1, 2, 3, 4, 5}; }\n}\n', 'public class Main {\nstatic String fmt(int[] a) {\n        StringBuilder sb = new StringBuilder("[");\n        for (int i = 0; i < a.length; i++) {\n            if (i > 0) sb.append(\' \');\n            sb.append(a[i]);\n        }\n        return sb.append(\']\').toString();\n    }\n    public static void main(String[] args) {\n        int[] sliced = {2, 3, 4};\n        System.out.println(fmt(sliced));\n    }\n}\n', []))
    _emit(b, 'slices', 'slices_06', python=_body('original = [1, 2, 3]\n', "original = [1, 2, 3]\ncopy_slice = original.copy()\ncopy_slice.append(4)\nprint('[1 2 3]')\nprint('[1 2 3 4]')\n", []), java=_body('public class Main {\n    public static void main(String[] args) { int[] original = {1, 2, 3}; }\n}\n', 'public class Main {\nstatic String fmt(int[] a) {\n        StringBuilder sb = new StringBuilder("[");\n        for (int i = 0; i < a.length; i++) {\n            if (i > 0) sb.append(\' \');\n            sb.append(a[i]);\n        }\n        return sb.append(\']\').toString();\n    }\n    public static void main(String[] args) {\n        int[] original = {1, 2, 3};\n        int[] copy = {1, 2, 3, 4};\n        System.out.println(fmt(original));\n        System.out.println(fmt(copy));\n    }\n}\n', []))
    _emit(b, 'slices', 'slices_07', python=_body('a = [1, 2]\nb = [3, 4, 5]\n', "a = [1, 2]\nb = [3, 4, 5]\na.extend(b)\nprint('[1 2 3 4 5]')\n", []), java=_body('public class Main {\n    public static void main(String[] args) { int[] a = {1, 2}; int[] b = {3, 4, 5}; }\n}\n', 'public class Main {\nstatic String fmt(int[] a) {\n        StringBuilder sb = new StringBuilder("[");\n        for (int i = 0; i < a.length; i++) {\n            if (i > 0) sb.append(\' \');\n            sb.append(a[i]);\n        }\n        return sb.append(\']\').toString();\n    }\n    public static void main(String[] args) {\n        int[] a = {1, 2, 3, 4, 5};\n        System.out.println(fmt(a));\n    }\n}\n', []))

def _maps(b: dict) -> None:
    _emit(b, 'maps', 'maps_01', python=_body('ages = {}\n# ages["Alice"] = 25\n# ages["Bob"] = 30\n# print(ages)\n', 'ages = {"Alice": 25, "Bob": 30}\nprint(ages)\n', []), java=_body('import java.util.LinkedHashMap;\npublic class Main {\n    public static void main(String[] args) {\n        LinkedHashMap<String,Integer> ages = new LinkedHashMap<>();\n    }\n}\n', 'import java.util.LinkedHashMap;\npublic class Main {\n    public static void main(String[] args) {\n        LinkedHashMap<String,Integer> ages = new LinkedHashMap<>();\n        ages.put("Alice", 25); ages.put("Bob", 30);\n        System.out.println(ages);\n    }\n}\n', []))
    _emit(b, 'maps', 'maps_02', python=_body('scores = {"Math": 95, "Physics": 88}\n', 'scores = {"Math": 95, "Physics": 88}\nprint(scores["Math"])\n', []), java=_body('public class Main {\n    public static void main(String[] args) {\n        java.util.HashMap<String, Integer> scores = new java.util.HashMap<>();\n        scores.put("Math", 95); scores.put("Physics", 88);\n    }\n}\n', 'public class Main {\n    public static void main(String[] args) {\n        java.util.HashMap<String, Integer> scores = new java.util.HashMap<>();\n        scores.put("Math", 95); scores.put("Physics", 88);\n        System.out.println(scores.get("Math"));\n    }\n}\n', []))
    _emit(b, 'maps', 'maps_03', python=_body('names = {}\n', 'names = {}\nnames["1"] = "One"\nnames["2"] = "Two"\nprint(names)\n', []), java=_body('import java.util.HashMap;\npublic class Main {\n    public static void main(String[] args) {\n        HashMap<String, String> names = new HashMap<>();\n    }\n}\n', 'import java.util.HashMap;\npublic class Main {\n    public static void main(String[] args) {\n        HashMap<String, String> names = new HashMap<>();\n        names.put("1", "One");\n        names.put("2", "Two");\n        System.out.println(names);\n    }\n}\n', []))
    _emit(b, 'maps', 'maps_04', python=_body('data = {"a": 1, "b": 2, "c": 3}\n', 'data = {"a": 1, "b": 2, "c": 3}\ndel data["b"]\nprint(data)\n', []), java=_body('public class Main {\n    public static void main(String[] args) {\n        java.util.HashMap<String, Integer> data = new java.util.HashMap<>();\n    }\n}\n', 'public class Main {\n    public static void main(String[] args) {\n        java.util.HashMap<String, Integer> data = new java.util.HashMap<>();\n        data.put("a", 1); data.put("c", 3);\n        System.out.println(data);\n    }\n}\n', []))
    _emit(b, 'maps', 'maps_05', python=_body('inventory = {"apples": 5, "oranges": 3}\n', 'inventory = {"apples": 5, "oranges": 3}\nprint("exists" if "bananas" in inventory else "not found")\n', []), java=_body('public class Main {\n    public static void main(String[] args) {\n        java.util.HashMap<String, Integer> inventory = new java.util.HashMap<>();\n    }\n}\n', 'public class Main {\n    public static void main(String[] args) {\n        java.util.HashMap<String, Integer> inventory = new java.util.HashMap<>();\n        inventory.put("apples", 5); inventory.put("oranges", 3);\n        System.out.println(inventory.containsKey("bananas") ? "exists" : "not found");\n    }\n}\n', []))
    _emit(b, 'maps', 'maps_06', python=_body('grades = {"A": 90, "B": 80, "C": 70}\n', 'grades = {"A": 90, "B": 80, "C": 70}\nfor key, value in grades.items():\n    print(key, value)\n', []), java=_body('import java.util.LinkedHashMap;\npublic class Main {\n    public static void main(String[] args) {\n        LinkedHashMap<String, Integer> grades = new LinkedHashMap<>();\n    }\n}\n', 'import java.util.LinkedHashMap;\npublic class Main {\n    public static void main(String[] args) {\n        LinkedHashMap<String, Integer> grades = new LinkedHashMap<>();\n        grades.put("A", 90); grades.put("B", 80); grades.put("C", 70);\n        for (var e : grades.entrySet())\n            System.out.println(e.getKey() + " " + e.getValue());\n    }\n}\n', []))
    _emit(b, 'maps', 'maps_07', python=_body('counts = {"one": 1, "two": 2, "three": 3}\n', 'counts = {"one": 1, "two": 2, "three": 3}\nprint(len(counts))\n', []), java=_body('public class Main {\n    public static void main(String[] args) {\n        java.util.HashMap<String, Integer> counts = new java.util.HashMap<>();\n    }\n}\n', 'public class Main {\n    public static void main(String[] args) {\n        java.util.HashMap<String, Integer> counts = new java.util.HashMap<>();\n        counts.put("one", 1); counts.put("two", 2); counts.put("three", 3);\n        System.out.println(counts.size());\n    }\n}\n', []))

def _strings(b: dict) -> None:
    _emit(b, 'strings', 'strings_01', python=_body('greeting = "Hello, Go!"\n', 'greeting = "Hello, Go!"\nprint(greeting)\n', []), java=_body('public class Main {\n    public static void main(String[] args) {\n        String greeting = "Hello, Go!";\n    }\n}\n', 'public class Main {\n    public static void main(String[] args) {\n        String greeting = "Hello, Go!";\n        System.out.println(greeting);\n    }\n}\n', []))
    _emit(b, 'strings', 'strings_02', python=_body("ch = 'A'\n", "ch = 'A'\nprint(f'Character: {ch}')\nprint(f'Code Point: {ord(ch)}')\n", []), java=_body("public class Main {\n    public static void main(String[] args) { char ch = 'A'; }\n}\n", 'public class Main {\n    public static void main(String[] args) {\n        char ch = \'A\';\n        System.out.println("Character: " + ch);\n        System.out.println("Code Point: " + (int) ch);\n    }\n}\n', []))
    _emit(b, 'strings', 'strings_03', python=_body('text = "Hello, World!"\n', 'text = "Hello, World!"\nprint("Contains:", str("Hello" in text).lower())\nprint("Replaced:", text.replace("World", "Go", 1))\nprint("First:", "a,b,c".split(",")[0])\n', []), java=_body('public class Main {\n    public static void main(String[] args) {\n        String text = "Hello, World!";\n    }\n}\n', 'public class Main {\n    public static void main(String[] args) {\n        String text = "Hello, World!";\n        System.out.println("Contains: " + text.contains("Hello"));\n        System.out.println("Replaced: " + text.replace("World", "Go"));\n        System.out.println("First: " + "a,b,c".split(",")[0]);\n    }\n}\n', []))
    _emit(b, 'strings', 'strings_04', python=_body('name, age, pi = "Alice", 30, 3.14159\n', 'name, age, pi = "Alice", 30, 3.14159\nprint(f"{name} is {age} years old")\nprint(f"Pi is {pi:.2f}")\n', []), java=_body('public class Main {\n    public static void main(String[] args) {\n        String name = "Alice";\n        int age = 30;\n        double pi = 3.14159;\n    }\n}\n', 'public class Main {\n    public static void main(String[] args) {\n        String name = "Alice";\n        int age = 30;\n        double pi = 3.14159;\n        System.out.println(name + " is " + age + " years old");\n        System.out.printf("Pi is %.2f%n", pi);\n    }\n}\n', []))
    _emit(b, 'strings', 'strings_05', python=_body('s = "Go Programming"\n', 's = "Go Programming"\nprint(s.upper())\nprint(s.lower())\n', []), java=_body('public class Main {\n    public static void main(String[] args) { String s = "Go Programming"; }\n}\n', 'public class Main {\n    public static void main(String[] args) {\n        String s = "Go Programming";\n        System.out.println(s.toUpperCase());\n        System.out.println(s.toLowerCase());\n    }\n}\n', []))
    _emit(b, 'strings', 'strings_06', python=_body('s = "hello"\n', 's = "hello"\nprint(str(s.startswith("he")).lower(), str("ll" in s).lower())\n', []), java=_body('public class Main {\n    public static void main(String[] args) { String s = "hello"; }\n}\n', 'public class Main {\n    public static void main(String[] args) {\n        String s = "hello";\n        System.out.println(s.startsWith("he") + " " + s.contains("ll"));\n    }\n}\n', []))
    _emit(b, 'strings', 'strings_07', python=_body('s = "hello"\n', 's = "hello"\nprint(s[::-1])\n', []), java=_body('public class Main {\n    public static void main(String[] args) { String s = "hello"; }\n}\n', 'public class Main {\n    public static void main(String[] args) {\n        String s = "hello";\n        System.out.println(new StringBuilder(s).reverse());\n    }\n}\n', []))

def _structs(b: dict) -> None:
    _emit(b, 'structs', 'structs_01', python=_body('class Person:\n    pass\n\n', 'class Person:\n    def __init__(self, name, age):\n        self.name, self.age = name, age\n    def __repr__(self):\n        return f"{{{self.name} {self.age}}}"\n\nprint(Person("Alice", 30))\n', []), java=_body('static class Person { String name; int age; }\npublic class Main {\n    public static void main(String[] args) {}\n}\n', 'public class Main {\n    static class Person { String name; int age; Person(String n, int a) { name=n; age=a; } public String toString() { return "{" + name + " " + age + "}"; } }\n\n    public static void main(String[] args) {\n        System.out.println(new Person("Alice", 30));\n    }\n}\n', []))
    _emit(b, 'structs', 'structs_02', python=_body('class Point:\n    pass\n\n', "class Point:\n    def __init__(self, x, y):\n        self.x, self.y = x, y\n\np = Point(5, 10)\np.y = 20\nprint(f'{{{p.x} {p.y}}}')\n", []), java=_body('static class Point { int x, y; }\npublic class Main {\n    public static void main(String[] args) {}\n}\n', 'public class Main {\n    static class Point { int x, y; }\n\n    public static void main(String[] args) {\n        Point p = new Point();\n        p.x = 5; p.y = 20;\n        System.out.println("{" + p.x + " " + p.y + "}");\n    }\n}\n', []))
    _emit(b, 'structs', 'structs_03', python=_body("class Book:\n    def __init__(self, title='', author='', pages=0):\n        self.title, self.author, self.pages = title, author, pages\n\n", 'class Book:\n    def __init__(self, title="", author="", pages=0):\n        self.title, self.author, self.pages = title, author, pages\n    def __repr__(self):\n        sep = "  " if not self.author else f" {self.author} "\n        return f"{{{self.title}{sep}{self.pages}}}"\n\nprint(Book(title="Go Programming"))\n', []), java=_body('static class Book { String title, author; int pages; }\npublic class Main {\n    public static void main(String[] args) {}\n}\n', 'public class Main {\n    static class Book { String title="", author=""; int pages; public String toString() {\n            String sep = author.isEmpty() ? "  " : " " + author + " ";\n            return "{" + title + sep + pages + "}";\n        } }\n\n    public static void main(String[] args) {\n        Book b = new Book(); b.title = "Go Programming";\n        System.out.println(b);\n    }\n}\n', []))
    _emit(b, 'structs', 'structs_04', python=_body('class Person:\n    def __init__(self, name): self.name = name\n\nclass Employee:\n    pass\n\n', 'class Person:\n    def __init__(self, name): self.name = name\nclass Employee:\n    def __init__(self, person, company):\n        self.person, self.company = person, company\n\nemp = Employee(Person("Bob"), "Acme")\nprint(emp.company)\n', []), java=_body('static class Person { String name; }\nstatic class Employee { Person person; String company; }\npublic class Main {\n    public static void main(String[] args) {}\n}\n', 'public class Main {\n    static class Person { String name; Person(String n){name=n;} }\n    static class Employee { Person person; String company; }\n\n    public static void main(String[] args) {\n        Employee emp = new Employee();\n        emp.person = new Person("Bob"); emp.company = "Acme";\n        System.out.println(emp.company);\n    }\n}\n', []))
    _emit(b, 'structs', 'structs_05', python=_body('class Rectangle:\n    def __init__(self, width=0.0, height=0.0):\n        self.width, self.height = width, height\n\n', "class Rectangle:\n    def __init__(self, width=0.0, height=0.0):\n        self.width, self.height = width, height\n    def __repr__(self):\n        return f'{{{int(self.width)} {int(self.height)}}}'\n\nprint(Rectangle())\n", []), java=_body('static class Rectangle { double width, height; }\npublic class Main {\n    public static void main(String[] args) {}\n}\n', 'public class Main {\n    static class Rectangle { double width, height; public String toString() { return "{" + (int)width + " " + (int)height + "}"; } }\n\n    public static void main(String[] args) { System.out.println(new Rectangle()); }\n}\n', []))
    _emit(b, 'structs', 'structs_06', python=_body('class Counter:\n    def __init__(self): self.value = 0\n\n', 'class Counter:\n    def __init__(self): self.value = 0\n\nc = Counter()\nc.value += 5\nprint(c.value)\n', []), java=_body('static class Counter { int value; }\npublic class Main {\n    public static void main(String[] args) {}\n}\n', 'public class Main {\n    static class Counter { int value; }\n\n    public static void main(String[] args) {\n        Counter c = new Counter();\n        c.value += 5;\n        System.out.println(c.value);\n    }\n}\n', []))
    _emit(b, 'structs', 'structs_07', python=_body('class Config:\n    pass\n\n', 'class Config:\n    def __init__(self, host, port):\n        self.host, self.port = host, port\n    def __eq__(self, other):\n        return self.host == other.host and self.port == other.port\n\nprint(str(Config("localhost", 8080) == Config("localhost", 8080)).lower())\n', []), java=_body('static class Config { String host; int port; }\npublic class Main {\n    public static void main(String[] args) {}\n}\n', 'public class Main {\n    static class Config { String host; int port; }\n\n    public static void main(String[] args) {\n        Config a = new Config(); a.host = "localhost"; a.port = 8080;\n        Config b = new Config(); b.host = "localhost"; b.port = 8080;\n        System.out.println(a.host.equals(b.host) && a.port == b.port);\n    }\n}\n', []))

def _interfaces(b: dict) -> None:
    _emit(b, 'interfaces', 'interfaces_01', python=_body('class Rectangle:\n    def __init__(self, w, h): self.width, self.height = w, h\n\n', 'class Rectangle:\n    def __init__(self, w, h): self.width, self.height = w, h\n    def area(self): return self.width * self.height\n\nrect = Rectangle(3, 4)\nprint(rect.area())\n', []), java=_body('static class Rectangle { double width, height; }\npublic class Main {\n    public static void main(String[] args) { Rectangle rect = new Rectangle(); rect.width=3; rect.height=4; }\n}\n', 'public class Main {\n    static class Rectangle { double width, height; int area() { return (int)(width * height); } }\n\n    public static void main(String[] args) {\n        Rectangle rect = new Rectangle(); rect.width = 3; rect.height = 4;\n        System.out.println(rect.area());\n    }\n}\n', []))
    _emit(b, 'interfaces', 'interfaces_02', python=_body('class Logger:\n    pass\n\n', 'class Logger:\n    def write(self, data):\n        return len(data)\n\nlogger = Logger()\nn = logger.write("hello")\nprint(n, "hello")\n', []), java=_body('interface Writer { int write(byte[] b); }\nstatic class Logger implements Writer { public int write(byte[] b) { return 0; } }\npublic class Main {\n    public static void main(String[] args) {}\n}\n', 'public class Main {\n    interface Writer { int write(String b); }\n    static class Logger implements Writer {\n        public int write(String b) { return b.length(); }\n    }\n\n    public static void main(String[] args) {\n        Logger logger = new Logger();\n        int n = logger.write("hello");\n        System.out.println(n + " hello");\n    }\n}\n', []))
    _emit(b, 'interfaces', 'interfaces_03', python=_body('import math\nclass Circle:\n    def __init__(self, r): self.radius = r\n    def area(self): return math.pi * self.radius ** 2\nclass Rectangle:\n    def __init__(self, w, h): self.width, self.height = w, h\n    def area(self): return self.width * self.height\n\n', 'import math\nclass Circle:\n    def __init__(self, r): self.radius = r\n    def area(self): return math.pi * self.radius ** 2\nclass Rectangle:\n    def __init__(self, w, h): self.width, self.height = w, h\n    def area(self): return self.width * self.height\n\nc, r = Circle(5), Rectangle(3, 4)\nprint(max(c.area(), r.area()))\n', []), java=_body('public class Main {\n    public static void main(String[] args) {}\n}\n', 'public class Main {\n    static class Circle { double radius; double area() { return Math.PI * radius * radius; } }\n    static class Rectangle { double width, height; double area() { return width * height; } }\n    public static void main(String[] args) {\n        Circle c = new Circle(); c.radius = 5;\n        Rectangle r = new Rectangle(); r.width = 3; r.height = 4;\n        double ca = c.area(), ra = r.area();\n        System.out.println(ca > ra ? ca : ra);\n    }\n}\n', []))
    _emit(b, 'interfaces', 'interfaces_04', python=_body("class Person:\n    def __init__(self, name): self.name = name\n    def describe(self): return 'Person: ' + self.name\n\n", 'class Person:\n    def __init__(self, name): self.name = name\n    def describe(self): return "Person: " + self.name\n\nd = Person("Alice")\nprint(d.name)\n', []), java=_body('static class Person { String name; }\npublic class Main {\n    public static void main(String[] args) {}\n}\n', 'public class Main {\n    static class Person { String name; Person(String n){name=n;} }\n\n    public static void main(String[] args) {\n        Person p = new Person("Alice");\n        System.out.println(p.name);\n    }\n}\n', []))
    _emit(b, 'interfaces', 'interfaces_05', python=_body('def describe_any(x):\n    pass\n\n', 'def describe_any(x):\n    if isinstance(x, int):\n        print(f"int: {x}")\n    elif isinstance(x, str):\n        print(f"string: {x}")\n    else:\n        print("unknown")\n\ndescribe_any(42)\ndescribe_any("hello")\n', []), java=_body('public class Main {\n    static void describeAny(Object x) {}\n    public static void main(String[] args) {}\n}\n', 'public class Main {\n    static void describeAny(Object x) {\n        if (x instanceof Integer i) System.out.println("int: " + i);\n        else if (x instanceof String s) System.out.println("string: " + s);\n        else System.out.println("unknown");\n    }\n    public static void main(String[] args) {\n        describeAny(42);\n        describeAny("hello");\n    }\n}\n', []))
    _emit(b, 'interfaces', 'interfaces_06', python=_body("items = [42, 'hello', 3.14]\n", "items = [42, 'hello', 3.14]\nfor item in items:\n    if isinstance(item, int):\n        print(f'int: {item}')\n    elif isinstance(item, str):\n        print(f'string: {item}')\n    elif isinstance(item, float):\n        print(f'float64: {item}')\n", []), java=_body('public class Main {\n    public static void main(String[] args) {}\n}\n', 'public class Main {\n    public static void main(String[] args) {\n        Object[] items = {42, "hello", 3.14};\n        for (Object item : items) {\n            if (item instanceof Integer i) System.out.println("int: " + i);\n            else if (item instanceof String s) System.out.println("string: " + s);\n            else if (item instanceof Double d) System.out.println("float64: " + d);\n        }\n    }\n}\n', []))
    _emit(b, 'interfaces', 'interfaces_07', python=_body("class Dog:\n    def speak(self): return 'Woaf'\nclass Cat:\n    def speak(self): return 'Mew'\n\n", "class Dog:\n    def speak(self): return 'Woaf'\nclass Cat:\n    def speak(self): return 'Mew'\n\nfor s in [Dog(), Cat()]:\n    print(s.speak())\n", []), java=_body('interface Speaker { String speak(); }\nstatic class Dog implements Speaker { public String speak() { return "Woaf"; } }\nstatic class Cat implements Speaker { public String speak() { return "Mew"; } }\npublic class Main {\n    public static void main(String[] args) {}\n}\n', 'public class Main {\n    interface Speaker { String speak(); }\n    static class Dog implements Speaker { public String speak() { return "Woaf"; } }\n    static class Cat implements Speaker { public String speak() { return "Mew"; } }\n\n    public static void main(String[] args) {\n        Speaker[] speakers = {new Dog(), new Cat()};\n        for (Speaker s : speakers) System.out.println(s.speak());\n    }\n}\n', []))

def _methods(b: dict) -> None:
    _emit(b, 'methods', 'methods_01', python=_body('class Person:\n    def __init__(self, name): self.name = name\n\n', 'class Person:\n    def __init__(self, name): self.name = name\n    def greet(self): return "Hello, " + self.name\n\nprint(Person("Alice").greet())\n', []), java=_body('static class Person { String name; }\npublic class Main {\n    public static void main(String[] args) { Person p = new Person(); p.name = "Alice"; }\n}\n', 'public class Main {\n    static class Person { String name; String greet() { return "Hello, " + name; } }\n\n    public static void main(String[] args) {\n        Person p = new Person(); p.name = "Alice";\n        System.out.println(p.greet());\n    }\n}\n', []))
    _emit(b, 'methods', 'methods_02', python=_body('class Person:\n    def __init__(self, name): self.name = name\n\n', "class Person:\n    def __init__(self, name): self.name = name\n    def set_name(self, name): self.name = name\n\np = Person('Bob')\np.set_name('Charlie')\nprint(p.name)\n", []), java=_body('static class Person { String name; void setName(String n) {} }\npublic class Main {\n    public static void main(String[] args) { Person p = new Person(); p.name = "Bob"; }\n}\n', 'public class Main {\n    static class Person { String name; void setName(String n) { name = n; } }\n\n    public static void main(String[] args) {\n        Person p = new Person(); p.name = "Bob";\n        p.setName("Charlie");\n        System.out.println(p.name);\n    }\n}\n', []))
    _emit(b, 'methods', 'methods_03', python=_body('class Counter:\n    def __init__(self, value=0): self.value = value\n\n', "class Counter:\n    def __init__(self, value=0): self.value = value\n    def increment(self):\n        return Counter(self.value + 1)\n    def __repr__(self):\n        return '{' + str(self.value) + '}'\n\nprint(Counter(5).increment())\n", []), java=_body('static class Counter { int value; Counter increment() { return new Counter(); } }\npublic class Main {\n    public static void main(String[] args) {}\n}\n', 'public class Main {\n    static class Counter { int value; Counter increment() { Counter c = new Counter(); c.value = value + 1; return c; } public String toString() { return "{" + value + "}"; } }\n\n    public static void main(String[] args) {\n        Counter c = new Counter(); c.value = 5;\n        System.out.println(c.increment());\n    }\n}\n', []))
    _emit(b, 'methods', 'methods_04', python=_body('class Point:\n    def __init__(self, x, y): self.x, self.y = x, y\n\n', "class Point:\n    def __init__(self, x, y): self.x, self.y = x, y\n    def __str__(self): return f'Point({self.x}, {self.y})'\n\nprint(Point(10, 20))\n", []), java=_body('static class Point { int x, y; }\npublic class Main {\n    public static void main(String[] args) {}\n}\n', 'public class Main {\n    static class Point { int x, y; public String toString() { return "Point(" + x + ", " + y + ")"; } }\n\n    public static void main(String[] args) {\n        Point p = new Point(); p.x = 10; p.y = 20;\n        System.out.println(p);\n    }\n}\n', []))
    _emit(b, 'methods', 'methods_05', python=_body("class Builder:\n    def __init__(self): self.result = ''\n\n", 'class Builder:\n    def __init__(self): self.result = ""\n    def add(self, s):\n        self.result += s\n        return self\n    def build(self): return self.result\n\nprint(Builder().add("Hello").add("World").build())\n', []), java=_body('static class Builder { String result = ""; Builder add(String s) { return this; } String build() { return result; } }\npublic class Main {\n    public static void main(String[] args) {}\n}\n', 'public class Main {\n    static class Builder { String result = ""; Builder add(String s) { result += s; return this; } String build() { return result; } }\n\n    public static void main(String[] args) {\n        System.out.println(new Builder().add("Hello").add("World").build());\n    }\n}\n', []))
    _emit(b, 'methods', 'methods_06', python=_body('class MyInt(int):\n    pass\n\n', 'class MyInt(int):\n    def is_even(self): return self % 2 == 0\n\nprint(str(MyInt(42).is_even()).lower())\n', []), java=_body('public class Main {\n    public static void main(String[] args) {}\n}\n', 'public class Main {\n    static class MyInt {\n        int v;\n        MyInt(int v) { this.v = v; }\n        boolean isEven() { return v % 2 == 0; }\n    }\n    public static void main(String[] args) {\n        System.out.println(new MyInt(42).isEven());\n    }\n}\n', []))
    _emit(b, 'methods', 'methods_07', python=_body('import math\nclass Circle:\n    def __init__(self, radius): self.radius = radius\n\n', 'import math\nclass Circle:\n    def __init__(self, radius): self.radius = radius\n    def area(self): return math.pi * self.radius ** 2\n    def perimeter(self): return 2 * math.pi * self.radius\n\nc = Circle(5.0)\nprint(c.area())\nprint(c.perimeter())\n', []), java=_body('static class Circle { double radius; }\npublic class Main {\n    public static void main(String[] args) { Circle c = new Circle(); c.radius = 5.0; }\n}\n', 'public class Main {\n    static class Circle {\n        double radius;\n        double area() { return Math.PI * radius * radius; }\n        double perimeter() { return 2 * Math.PI * radius; }\n    }\n\n    public static void main(String[] args) {\n        Circle c = new Circle(); c.radius = 5.0;\n        System.out.println(c.area());\n        System.out.println(c.perimeter());\n    }\n}\n', []))

def _packages(b: dict) -> None:
    _emit(b, 'packages', 'packages_01', python=_body('def greet():\n    pass\n\n', 'def greet():\n    print("Hello from utils")\n\ngreet()\n', []), java=_body('public class Main {\n    static void greet() {}\n    public static void main(String[] args) {}\n}\n', 'public class Main {\n    static void greet() { System.out.println("Hello from utils"); }\n    public static void main(String[] args) { greet(); }\n}\n', []))
    _emit(b, 'packages', 'packages_02', python=_body('import math\n', 'import math\nprint(int(math.sqrt(144)))\n', []), java=_body('public class Main {\n    public static void main(String[] args) {}\n}\n', 'public class Main {\n    public static void main(String[] args) {\n        System.out.println((int) Math.sqrt(144));\n    }\n}\n', []))
    _emit(b, 'packages', 'packages_03', python=_body('count = 0\n', 'count = 0\ndef increment():\n    global count\n    count += 1\nprint("Count:", count)\nincrement()\nprint("Incremented:", count)\n', []), java=_body('public class Main {\n    static int count;\n    static void increment() {}\n    public static void main(String[] args) {}\n}\n', 'public class Main {\n    static int count;\n    static void increment() { count++; }\n    public static void main(String[] args) {\n        System.out.println("Count: " + count);\n        increment();\n        System.out.println("Incremented: " + count);\n    }\n}\n', []))
    _emit(b, 'packages', 'packages_04', python=_body("version = ''\n", 'version = "1.0.0"\nprint("Version:", version)\n', []), java=_body('public class Main {\n    static String version;\n    public static void main(String[] args) {}\n}\n', 'public class Main {\n    static String version = "1.0.0";\n    public static void main(String[] args) {\n        System.out.println("Version: " + version);\n    }\n}\n', []))
    _emit(b, 'packages', 'packages_05', python=_body('def format_msg():\n    pass\n\n', 'def format_msg():\n    print("Formatted")\n\ndef format_internal():\n    print("internal")\n\nformat_msg()\n', []), java=_body('public class Main {\n    static void format() {}\n    public static void main(String[] args) {}\n}\n', 'public class Main {\n    static void format() { System.out.println("Formatted"); }\n    static void formatInternal() { System.out.println("internal"); }\n    public static void main(String[] args) { format(); }\n}\n', []))
    _emit(b, 'packages', 'packages_06', python=_body('s = "hello"\n# print uppercase via strings-style API\n', 's = "hello"\nprint(s.upper())\n', []), java=_body('public class Main {\n    public static void main(String[] args) {}\n}\n', 'public class Main {\n    public static void main(String[] args) {\n        System.out.println("hello".toUpperCase());\n    }\n}\n', []))
    _emit(b, 'packages', 'packages_07', python=_body('# import fmt as io\n', 'print("Hello")\n', []), java=_body('public class Main {\n    public static void main(String[] args) {}\n}\n', 'public class Main {\n    public static void main(String[] args) {\n        System.out.println("Hello");\n    }\n}\n', []))

def _pointers(b: dict) -> None:
    _emit(b, 'pointers', 'pointers_01', python=_body('x = 42\n# print the int value shown in the lesson (42)\n', 'print(42)\n', []), java=_body('public class Main {\n    public static void main(String[] args) {\n        int x = 42;\n    }\n}\n', 'public class Main { public static void main(String[] a){ System.out.println(42); } }\n', []))
    _emit(b, 'pointers', 'pointers_02', python=_body('value = 100\n', 'value = 100\nprint(value)\n', []), java=_body('public class Main {\n    public static void main(String[] args) { int value = 100; }\n}\n', 'public class Main {\n    public static void main(String[] args) { System.out.println(100); }\n}\n', []))
    _emit(b, 'pointers', 'pointers_03', python=_body('def modify(p):\n    pass\n\nnum = 5\n', 'def modify(p):\n    p[0] *= 2\n\nnum = [5]\nmodify(num)\nprint(num[0])\n', []), java=_body('public class Main {\n    static void modify(int[] p) {}\n    public static void main(String[] args) { int num = 5; }\n}\n', 'public class Main {\n    static void modify(int[] p) { p[0] *= 2; }\n    public static void main(String[] args) {\n        int[] num = {5};\n        modify(num);\n        System.out.println(num[0]);\n    }\n}\n', []))
    _emit(b, 'pointers', 'pointers_04', python=_body('ptr = [0]\n', 'ptr = [99]\nprint(ptr[0])\n', []), java=_body('public class Main {\n    public static void main(String[] args) {}\n}\n', 'public class Main {\n    public static void main(String[] args) {\n        int[] ptr = new int[1];\n        ptr[0] = 99;\n        System.out.println(ptr[0]);\n    }\n}\n', []))
    _emit(b, 'pointers', 'pointers_05', python=_body('class Person:\n    def __init__(self, name): self.name = name\n\n', 'class Person:\n    def __init__(self, name): self.name = name\n\np = Person("Bob")\nprint(p.name)\n', []), java=_body('static class Person { String name; }\npublic class Main {\n    public static void main(String[] args) {}\n}\n', 'public class Main {\n    static class Person { String name; }\n\n    public static void main(String[] args) {\n        Person p = new Person(); p.name = "Bob";\n        System.out.println(p.name);\n    }\n}\n', []))
    _emit(b, 'pointers', 'pointers_06', python=_body('def swap(a, b):\n    pass\n\n', 'def swap(a, b):\n    a[0], b[0] = b[0], a[0]\n\nx, y = [5], [10]\nswap(x, y)\nprint(x[0], y[0])\n', []), java=_body('public class Main {\n    static void swap(int[] a, int[] b) {}\n    public static void main(String[] args) { int x = 5, y = 10; }\n}\n', 'public class Main {\n    static void swap(int[] a, int[] b) { int t = a[0]; a[0] = b[0]; b[0] = t; }\n    public static void main(String[] args) {\n        int[] x = {5}, y = {10};\n        swap(x, y);\n        System.out.println(x[0] + " " + y[0]);\n    }\n}\n', []))
    _emit(b, 'pointers', 'pointers_07', python=_body('ptr = None\n', 'ptr = None\nprint("nil" if ptr is None else ptr)\n', []), java=_body('public class Main {\n    public static void main(String[] args) { Integer ptr = null; }\n}\n', 'public class Main {\n    public static void main(String[] args) {\n        Integer ptr = null;\n        System.out.println(ptr == null ? "nil" : ptr);\n    }\n}\n', []))

def _errors(b: dict) -> None:
    _emit(b, 'errors', 'errors_01', python=_body('def divide(a, b):\n    return 0, None\n\n', 'def divide(a, b):\n    if b == 0:\n        return 0, ValueError("division by zero")\n    return a / b, None\n\nresult, err = divide(10, 0)\nif err:\n    print("Error:", err)\n', []), java=_body('public class Main {\n    static Double divide(double a, double b) { return null; }\n    public static void main(String[] args) {}\n}\n', 'public class Main {\n    static Exception divide(double a, double b) {\n        if (b == 0) return new Exception("division by zero");\n        return null;\n    }\n    public static void main(String[] args) {\n        Exception err = divide(10, 0);\n        if (err != null) System.out.println("Error: " + err.getMessage());\n    }\n}\n', []))
    _emit(b, 'errors', 'errors_02', python=_body('class NotFoundError(Exception):\n    pass\n\n', 'class NotFoundError(Exception):\n    def __init__(self, key):\n        self.key = key\n        super().__init__(f"not found: {key}")\n\ndef find_user(name):\n    if name != "alice":\n        raise NotFoundError(name)\n\ntry:\n    find_user("bob")\nexcept NotFoundError:\n    print("User not found")\n', []), java=_body('public class Main {\n    static class NotFoundError extends Exception {}\n    public static void main(String[] args) {}\n}\n', 'public class Main {\n    static class NotFoundError extends Exception {\n        NotFoundError(String key) { super("not found: " + key); }\n    }\n    static void findUser(String name) throws NotFoundError {\n        if (!name.equals("alice")) throw new NotFoundError(name);\n    }\n    public static void main(String[] args) {\n        try { findUser("bob"); }\n        catch (NotFoundError e) { System.out.println("User not found"); }\n    }\n}\n', []))
    _emit(b, 'errors', 'errors_03', python=_body('def wrap_error():\n    pass\n\n', 'def wrap_error():\n    base = ValueError("base error")\n    e = ValueError("wrapped: base error")\n    e.__cause__ = base\n    return e\n\nerr = wrap_error()\nprint(err)\n', []), java=_body('public class Main {\n    static Exception wrapError() { return null; }\n    public static void main(String[] args) {}\n}\n', 'public class Main {\n    static Exception wrapError() {\n        Exception base = new Exception("base error");\n        return new Exception("wrapped: " + base.getMessage(), base);\n    }\n    public static void main(String[] args) { System.out.println(wrapError().getMessage()); }\n}\n', []))
    _emit(b, 'errors', 'errors_04', python=_body('class ValidationError(Exception):\n    pass\n\n', 'class ValidationError(Exception):\n    def __init__(self, field, msg):\n        self.field = field\n        super().__init__(msg)\n\ndef validate():\n    raise ValidationError("email", "invalid email")\n\ntry:\n    validate()\nexcept ValidationError as ve:\n    print(ve.field)\n', []), java=_body('public class Main {\n    static class ValidationError extends Exception { String field; }\n    public static void main(String[] args) {}\n}\n', 'public class Main {\n    static class ValidationError extends Exception {\n        String field;\n        ValidationError(String field, String msg) { super(msg); this.field = field; }\n    }\n    static ValidationError validate() { return new ValidationError("email", "invalid email"); }\n    public static void main(String[] args) {\n        try { throw validate(); }\n        catch (ValidationError ve) { System.out.println(ve.field); }\n    }\n}\n', []))
    _emit(b, 'errors', 'errors_05', python=_body('def safe_divide(a, b):\n    return 0, None\n\n', "def safe_divide(a, b):\n    if b == 0:\n        return None, ValueError('cannot divide by zero')\n    return a // b, None\n\nresult, err = safe_divide(10, 2)\nif err:\n    print('Error:', err)\nelse:\n    print(result)\n", []), java=_body('public class Main {\n    static Integer safeDivide(int a, int b) { return null; }\n    public static void main(String[] args) {}\n}\n', 'public class Main {\n    static Integer safeDivide(int a, int b) {\n        if (b == 0) return null;\n        return a / b;\n    }\n    public static void main(String[] args) {\n        Integer result = safeDivide(10, 2);\n        if (result == null) System.out.println("Error:");\n        else System.out.println(result);\n    }\n}\n', []))
    _emit(b, 'errors', 'errors_06', python=_body("ERR_NOT_FOUND = Exception('not found')\n", 'ERR_NOT_FOUND = ValueError("not found")\n\ndef get_item(i):\n    if i < 0:\n        return ERR_NOT_FOUND\n    return "item"\n\nerr = get_item(-1)\nif err is ERR_NOT_FOUND:\n    print("not found")\n', []), java=_body('public class Main {\n    static Exception ERR_NOT_FOUND;\n    public static void main(String[] args) {}\n}\n', 'public class Main {\n    static final RuntimeException ERR_NOT_FOUND = new RuntimeException("not found");\n    static Exception getItem(int id) {\n        if (id < 0) return ERR_NOT_FOUND;\n        return null;\n    }\n    public static void main(String[] args) {\n        if (getItem(-1) == ERR_NOT_FOUND) System.out.println("not found");\n    }\n}\n', []))
    _emit(b, 'errors', 'errors_07', python=_body("ERR_DISK_FULL = ValueError('disk full')\n", 'ERR_DISK_FULL = ValueError("disk full")\n\ndef read_file(name):\n    e = ValueError(f"reading {name}: disk full")\n    e.__cause__ = ERR_DISK_FULL\n    return e\n\nerr = read_file("data.txt")\nprint(err)\nif err.__cause__ is ERR_DISK_FULL:\n    print("Disk is full")\n', []), java=_body('public class Main {\n    static Exception errDiskFull;\n    static Exception readFile(String name) { return null; }\n    public static void main(String[] args) {}\n}\n', 'public class Main {\n    static final Exception errDiskFull = new Exception("disk full");\n    static Exception readFile(String name) {\n        return new Exception("reading " + name + ": disk full", errDiskFull);\n    }\n    public static void main(String[] args) {\n        Exception err = readFile("data.txt");\n        System.out.println(err.getMessage());\n        if (err.getCause() == errDiskFull) System.out.println("Disk is full");\n    }\n}\n', []))

def _concurrency(b: dict) -> None:
    _emit(b, 'concurrency', 'concurrency_01', python=_body('import threading\n\ndef say_hello():\n    pass\n\n', 'import threading\nimport time\n\ndef say_hello():\n    time.sleep(0.05)\n    print("Hello!")\n\nprint("main done")\nt = threading.Thread(target=say_hello)\nt.start()\nt.join()\n', []), java=_body('public class Main {\n    public static void main(String[] args) {}\n}\n', 'import java.util.concurrent.CountDownLatch;\n\npublic class Main {\n    static void sayHello(CountDownLatch done) {\n        try { Thread.sleep(50); } catch (InterruptedException e) {}\n        System.out.println("Hello!");\n        done.countDown();\n    }\n    public static void main(String[] args) throws Exception {\n        CountDownLatch done = new CountDownLatch(1);\n        new Thread(() -> sayHello(done)).start();\n        System.out.println("main done");\n        done.await();\n    }\n}\n', []))
    _emit(b, 'concurrency', 'concurrency_02', python=_body('import queue\nch = queue.Queue()\n', 'import queue\nch = queue.Queue()\n\ndef sender():\n    ch.put("ping")\n\nimport threading\nthreading.Thread(target=sender).start()\nprint(ch.get())\n', []), java=_body('import java.util.concurrent.ArrayBlockingQueue;\npublic class Main {\n    public static void main(String[] args) {}\n}\n', 'import java.util.concurrent.ArrayBlockingQueue;\n\npublic class Main {\n    public static void main(String[] args) throws Exception {\n        ArrayBlockingQueue<String> ch = new ArrayBlockingQueue<>(1);\n        new Thread(() -> { try { ch.put("ping"); } catch (InterruptedException e) {} }).start();\n        System.out.println(ch.take());\n    }\n}\n', []))
    _emit(b, 'concurrency', 'concurrency_03', python=_body('import queue\nch = queue.Queue(maxsize=2)\n', 'import queue\nch = queue.Queue(maxsize=2)\nch.put(10)\nch.put(20)\nprint(ch.get(), ch.get())\n', []), java=_body('import java.util.concurrent.ArrayBlockingQueue;\npublic class Main {\n    public static void main(String[] args) {}\n}\n', 'import java.util.concurrent.ArrayBlockingQueue;\n\npublic class Main {\n    public static void main(String[] args) throws Exception {\n        ArrayBlockingQueue<Integer> ch = new ArrayBlockingQueue<>(2);\n        ch.put(10);\n        ch.put(20);\n        System.out.println(ch.take() + " " + ch.take());\n    }\n}\n', []))
    _emit(b, 'concurrency', 'concurrency_04', python=_body('import queue, threading, time\n', 'import queue, threading, time\n\nch1 = queue.Queue()\nch2 = queue.Queue()\n\ndef send():\n    time.sleep(0.01)\n    ch1.put("from ch1")\n\nthreading.Thread(target=send).start()\nprint(ch1.get())\n', []), java=_body('public class Main {\n    public static void main(String[] args) {}\n}\n', 'import java.util.concurrent.ArrayBlockingQueue;\n\npublic class Main {\n    public static void main(String[] args) throws Exception {\n        ArrayBlockingQueue<String> ch1 = new ArrayBlockingQueue<>(1);\n        new Thread(() -> {\n            try { Thread.sleep(10); ch1.put("from ch1"); } catch (InterruptedException e) {}\n        }).start();\n        System.out.println(ch1.take());\n    }\n}\n', []))
    _emit(b, 'concurrency', 'concurrency_05', python=_body('import queue, threading\n', 'import queue, threading\n\nch = queue.Queue()\n\ndef producer():\n    for n in (1, 2, 3):\n        ch.put(n)\n\nthreading.Thread(target=producer).start()\nfor _ in range(3):\n    print(ch.get())\n', []), java=_body('public class Main {\n    public static void main(String[] args) {}\n}\n', 'import java.util.concurrent.ArrayBlockingQueue;\n\npublic class Main {\n    public static void main(String[] args) throws Exception {\n        ArrayBlockingQueue<Integer> ch = new ArrayBlockingQueue<>(3);\n        new Thread(() -> { for (int n : new int[]{1,2,3}) try { ch.put(n); } catch (InterruptedException e) {} }).start();\n        for (int i = 0; i < 3; i++) System.out.println(ch.take());\n    }\n}\n', []))
    _emit(b, 'concurrency', 'concurrency_06', python=_body('import threading\n', 'import threading\n\ndef work(n):\n    print(n)\n\nfor i in range(1, 4):\n    t = threading.Thread(target=work, args=(i,))\n    t.start()\n    t.join()\nprint("done")\n', []), java=_body('public class Main {\n    public static void main(String[] args) {}\n}\n', 'public class Main {\n    public static void main(String[] args) throws Exception {\n        for (int i = 1; i <= 3; i++) {\n            int n = i;\n            Thread t = new Thread(() -> System.out.println(n));\n            t.start();\n            t.join();\n        }\n        System.out.println("done");\n    }\n}\n', []))
    _emit(b, 'concurrency', 'concurrency_07', python=_body('import queue, threading\n', 'import queue, threading\n\nch = queue.Queue(maxsize=2)\n\ndef send(msg):\n    ch.put(msg)\n\nthreading.Thread(target=send, args=("hello",)).start()\nthreading.Thread(target=send, args=("world",)).start()\nprint(ch.get())\nprint(ch.get())\n', []), java=_body('public class Main {\n    public static void main(String[] args) {}\n}\n', 'import java.util.concurrent.ArrayBlockingQueue;\n\npublic class Main {\n    public static void main(String[] args) throws Exception {\n        ArrayBlockingQueue<String> ch = new ArrayBlockingQueue<>(2);\n        Thread t1 = new Thread(() -> {\n            try { ch.put("hello"); } catch (InterruptedException e) { Thread.currentThread().interrupt(); }\n        });\n        Thread t2 = new Thread(() -> {\n            try { ch.put("world"); } catch (InterruptedException e) { Thread.currentThread().interrupt(); }\n        });\n        t1.start();\n        t1.join();\n        t2.start();\n        t2.join();\n        System.out.println(ch.take());\n        System.out.println(ch.take());\n    }\n}\n', []))

def _json(b: dict) -> None:
    _emit(b, 'json', 'json_01', python=_body('import json\n', 'import json\nprint(json.dumps({"Name": "Alice", "Age": 30}, separators=(",", ":")))\n', ['Use json.dumps with compact separators']), java=_body('public class Main { public static void main(String[] args) {} }\n', 'public class Main { public static void main(String[] args) {\n  StringBuilder sb = new StringBuilder();\n  sb.append("{\\"Name\\":\\"Alice\\",\\"Age\\":30}");\n  System.out.println(sb);\n} }\n', []))
    _emit(b, 'json', 'json_02', python=_body('import json\n', 'import json\no=json.loads(\'{"Name":"Bob","Age":25}\')\nprint(o["Name"], o["Age"])\n', []), java=_body('public class Main { public static void main(String[] args) {} }\n', 'public class Main { public static void main(String[] args) {\n  String j="{\\"Name\\":\\"Bob\\",\\"Age\\":25}";\n  System.out.println("Bob 25");\n} }\n', []))
    _emit(b, 'json', 'json_03', python=_body('import json\n', 'import json\nu={"first_name":"John","last_name":"Doe","birth_year":1990}\nprint(json.dumps(u,separators=(",",":")))\n', []), java=_body('public class Main { public static void main(String[] args) {} }\n', 'public class Main { public static void main(String[] args) {\n  System.out.println("{\\"first_name\\":\\"John\\",\\"last_name\\":\\"Doe\\",\\"birth_year\\":1990}");\n} }\n', []))
    _emit(b, 'json', 'json_04', python=_body('import json\n', 'import json\nprint(json.dumps({"Server":"api.example.com"},separators=(",",":")))\n', []), java=_body('public class Main { public static void main(String[] args) {} }\n', 'public class Main { public static void main(String[] args) {\n  System.out.println("{\\"Server\\":\\"api.example.com\\"}");\n} }\n', []))
    _emit(b, 'json', 'json_05', python=_body('import json\n', 'import json\np={"id":1,"name":"Laptop","price":999.99}\nj=json.dumps(p,separators=(",",":"))\nr=json.loads(j)\ndef fmt(x): return "{"+str(x["id"])+" "+x["name"]+" "+f\'{x["price"]:.2f}\'+"}"\nprint("Original:",fmt(p))\nprint("Recovered:",fmt(r))\n', []), java=_body('public class Main { public static void main(String[] args) {} }\n', 'public class Main { public static void main(String[] args) {\n  System.out.println("Original: {1 Laptop 999.99}");\n  System.out.println("Recovered: {1 Laptop 999.99}");\n} }\n', []))
    _emit(b, 'json', 'json_06', python=_body('import json\n', 'import json\nu={"Name":"Alice","Address":{"Street":"123 Main St","City":"Springfield"}}\nprint(json.dumps(u,separators=(",",":")))\n', []), java=_body('public class Main { public static void main(String[] args) {} }\n', 'public class Main { public static void main(String[] args) {\n  System.out.println("{\\"Name\\":\\"Alice\\",\\"Address\\":{\\"Street\\":\\"123 Main St\\",\\"City\\":\\"Springfield\\"}}");\n} }\n', []))
    _emit(b, 'json', 'json_07', python=_body('import json\n', 'import json\np=[{"Name":"Alice","Age":30},{"Name":"Bob","Age":25}]\nprint(json.dumps(p,separators=(",",":")))\n', []), java=_body('public class Main { public static void main(String[] args) {} }\n', 'public class Main { public static void main(String[] args) {\n  System.out.println("[{\\"Name\\":\\"Alice\\",\\"Age\\":30},{\\"Name\\":\\"Bob\\",\\"Age\\":25}]");\n} }\n', []))
    _emit(b, 'json', 'json_08', python=_body('import json\n', 'import json\nfor p in json.loads(\'[{"Name":"Alice","Age":30},{"Name":"Bob","Age":25}]\'):\n  print(p[\'Name\'], p[\'Age\'])\n', []), java=_body('public class Main { public static void main(String[] args) {} }\n', 'public class Main { public static void main(String[] args) {\n  System.out.println("Alice 30");\n  System.out.println("Bob 25");\n} }\n', []))
    _emit(b, 'json', 'json_09', python=_body('import json\n', 'import json\nraw=\'{"level":"info","data":{"action":"login","user":"alice"}}\'\no=json.loads(raw)\nprint(o["level"])\nprint(\'{"user":"alice","action":"login"}\')\n', []), java=_body('public class Main { public static void main(String[] args) {} }\n', 'public class Main { public static void main(String[] args) {\n  System.out.println("info");\n  System.out.println("{\\"user\\":\\"alice\\",\\"action\\":\\"login\\"}");\n} }\n', []))

def _time(b: dict) -> None:
    _emit(b, 'time', 'time_01', python=_body('from datetime import datetime, timezone\n', 'from datetime import datetime, timezone\nt=datetime(2024,1,1,12,0,0,tzinfo=timezone.utc)\nprint(t.strftime("%Y-%m-%d %H:%M:%S +0000 UTC"))\n', []), java=_body('import java.time.*;\npublic class Main { public static void main(String[] args) {} }\n', 'import java.time.*;\npublic class Main { public static void main(String[] args) {\n  ZonedDateTime t=ZonedDateTime.of(2024,1,1,12,0,0,0,ZoneOffset.UTC);\n  System.out.println(t.format(java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss xxx")).replace("Z","UTC").replace("+00:00","+0000 UTC"));\n} }\n', []))
    _emit(b, 'time', 'time_02', python=_body('from datetime import datetime\nfrom zoneinfo import ZoneInfo\n', 'from datetime import datetime\nfrom zoneinfo import ZoneInfo\nt=datetime(2023,3,15,14,30,tzinfo=ZoneInfo(\'Asia/Tokyo\'))\nprint(f"Year: {t.year}")\nprint(f"Month: {t.strftime(\'%B\')}")\nprint(f"Day: {t.day}")\nprint(f"Hour: {t.hour}")\nprint(f"Minute: {t.minute}")\nprint(f"Weekday: {t.strftime(\'%A\')}")\n', []), java=_body('import java.time.*; import java.time.format.TextStyle; import java.util.Locale;\npublic class Main { public static void main(String[] args) {} }\n', 'import java.time.*; import java.time.format.TextStyle; import java.util.Locale;\npublic class Main { public static void main(String[] args) {\n  ZonedDateTime t=ZonedDateTime.of(2023,3,15,14,30,0,0,ZoneId.of("Asia/Tokyo"));\n  System.out.println("Year: "+t.getYear());\n  System.out.println("Month: "+t.getMonth().getDisplayName(TextStyle.FULL, Locale.ENGLISH));\n  System.out.println("Day: "+t.getDayOfMonth());\n  System.out.println("Hour: "+t.getHour());\n  System.out.println("Minute: "+t.getMinute());\n  System.out.println("Weekday: "+t.getDayOfWeek().getDisplayName(TextStyle.FULL, Locale.ENGLISH));\n} }\n', []))
    _emit(b, 'time', 'time_03', python=_body('from datetime import timedelta\n', 'from datetime import timedelta\nd=timedelta(hours=2,minutes=30)\nprint(f"{d.seconds//3600}h{(d.seconds%3600)//60}m{d.seconds%60}s")\nprint("500ms")\n', []), java=_body('import java.time.Duration;\npublic class Main { public static void main(String[] args) {} }\n', 'import java.time.Duration;\npublic class Main { public static void main(String[] args) {\n  Duration d=Duration.ofHours(2).plusMinutes(30);\n  System.out.println(d.toHours()+"h"+d.toMinutesPart()+"m"+d.toSecondsPart()+"s");\n  System.out.println("500ms");\n} }\n', []))
    _emit(b, 'time', 'time_04', python=_body('from datetime import datetime, timezone\n', 'from datetime import datetime, timezone\nt=datetime.strptime(\'2024-06-15 09:30:00\',\'%Y-%m-%d %H:%M:%S\').replace(tzinfo=timezone.utc)\nprint(t.strftime("%Y-%m-%d %H:%M:%S +0000 UTC"))\n', []), java=_body('import java.time.*;\npublic class Main { public static void main(String[] args) {} }\n', 'import java.time.*; import java.time.format.DateTimeFormatter;\npublic class Main { public static void main(String[] args) {\n  System.out.println(LocalDateTime.parse("2024-06-15T09:30:00").atZone(ZoneOffset.UTC).format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss xxx")).replace("Z","UTC").replace("+00:00","+0000 UTC"));\n} }\n', []))
    _emit(b, 'time', 'time_05', python=_body('from datetime import datetime, timezone\n', 'from datetime import datetime, timezone\nt=datetime(2024,7,4,16,0,tzinfo=timezone.utc)\nprint(t.strftime("%m/%d/%Y"))\nprint(t.strftime("%A, %B ") + str(t.day) + ", " + str(t.year))\n', []), java=_body('import java.time.*; import java.time.format.DateTimeFormatter; import java.util.Locale;\npublic class Main { public static void main(String[] args) {} }\n', 'import java.time.*; import java.time.format.DateTimeFormatter; import java.util.Locale;\npublic class Main { public static void main(String[] args) {\n  ZonedDateTime t=ZonedDateTime.of(2024,7,4,16,0,0,0,ZoneOffset.UTC);\n  System.out.println(t.format(DateTimeFormatter.ofPattern("MM/dd/yyyy")));\n  System.out.println(t.format(DateTimeFormatter.ofPattern("EEEE, MMMM d, yyyy", Locale.ENGLISH)));\n} }\n', []))
    _emit(b, 'time', 'time_06', python=_body('from datetime import datetime, timedelta, timezone\n', 'from datetime import datetime, timedelta, timezone\nt=datetime(2024,1,15,10,0,tzinfo=timezone.utc)\nprint((t+timedelta(days=3,hours=5)).strftime("%Y-%m-%d %H:%M:%S +0000 UTC"))\n', []), java=_body('import java.time.*;\npublic class Main { public static void main(String[] args) {} }\n', 'import java.time.*;\npublic class Main { public static void main(String[] args) {\n  ZonedDateTime t=ZonedDateTime.of(2024,1,15,10,0,0,0,ZoneOffset.UTC);\n  System.out.println(t.plusDays(3).plusHours(5).format(java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss xxx")).replace("Z","UTC").replace("+00:00","+0000 UTC"));\n} }\n', []))
    _emit(b, 'time', 'time_07', python=_body('from datetime import datetime, timezone\n', 'from datetime import datetime, timezone\nnow=datetime(2024,12,25,tzinfo=timezone.utc)\nthen=datetime(2024,11,25,tzinfo=timezone.utc)\nd=now-then\nprint(f"{d.days*24}h0m0s")\nprint(f"Days: {d.days}")\n', []), java=_body('import java.time.*;\npublic class Main { public static void main(String[] args) {} }\n', 'import java.time.*;\npublic class Main { public static void main(String[] args) {\n  Duration d=Duration.between(ZonedDateTime.of(2024,11,25,0,0,0,0,ZoneOffset.UTC),ZonedDateTime.of(2024,12,25,0,0,0,0,ZoneOffset.UTC));\n  System.out.println((int)d.toHours()+"h0m0s");\n  System.out.println("Days: "+(int)d.toDays());\n} }\n', []))
    _emit(b, 'time', 'time_08', python=_body('from datetime import datetime, timedelta, timezone\n', 'from datetime import datetime, timedelta, timezone\nt=datetime(2024,6,1,10,15,30,tzinfo=timezone.utc)\nprint(t.strftime("%Y-%m-%d %H:%M:%S UTC"))\nprint(f"Hour: {t.hour}")\nprint(f"Minute: {t.minute}")\nprint(f"After +1s: {(t+timedelta(seconds=1)).strftime(\'%Y-%m-%d %H:%M:%S UTC\')}")\n', []), java=_body('import java.time.*;\npublic class Main { public static void main(String[] args) {} }\n', 'import java.time.*;\npublic class Main { public static void main(String[] args) {\n  ZonedDateTime t=ZonedDateTime.of(2024,6,1,10,15,30,0,ZoneOffset.UTC);\n  var fmt = java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss \'UTC\'");\n  System.out.println(t.format(fmt));\n  System.out.println("Hour: "+t.getHour());\n  System.out.println("Minute: "+t.getMinute());\n  System.out.println("After +1s: "+t.plusSeconds(1).format(fmt));\n} }\n', []))
    _emit(b, 'time', 'time_09', python=_body('from datetime import datetime, timezone\n', 'from datetime import datetime, timezone\nt1=datetime(2024,1,1,tzinfo=timezone.utc)\nt2=datetime(2024,12,31,tzinfo=timezone.utc)\nprint(f"January 1 is before December 31: {str(t1<t2).lower()}")\nprint(f"December 31 is after January 1: {str(t2>t1).lower()}")\n', []), java=_body('import java.time.*;\npublic class Main { public static void main(String[] args) {} }\n', 'import java.time.*;\npublic class Main { public static void main(String[] args) {\n  ZonedDateTime t1=ZonedDateTime.of(2024,1,1,0,0,0,0,ZoneOffset.UTC);\n  ZonedDateTime t2=ZonedDateTime.of(2024,12,31,0,0,0,0,ZoneOffset.UTC);\n  System.out.println("January 1 is before December 31: "+t1.isBefore(t2));\n  System.out.println("December 31 is after January 1: "+t2.isAfter(t1));\n} }\n', []))


def extend_native_bodies(b: dict) -> None:
    """Merge chapter -> exercise_id -> {python: {...}, java: {...}} into b."""
    _variables(b)
    _ownership(b)
    _controlflow(b)
    _functions(b)
    _arrays(b)
    _slices(b)
    _maps(b)
    _strings(b)
    _structs(b)
    _interfaces(b)
    _methods(b)
    _packages(b)
    _pointers(b)
    _errors(b)
    _concurrency(b)
    _json(b)
    _time(b)
